eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8866
spring:
  application:
    name: glmapper-cloud-gateway
  cloud:
    gateway:
      routes:
      - id: glmapper
        uri: http://localhost:8086/hello
        predicates:
        - Path=/gateway
